### ISSUE TITLE
Plans for tutorials 20-plus?

### ISSUE THREAD

**Issue by bhagerty** [elifieldsteel/SuperCollider-Tutorials#2]
I'm wondering if you plan to provide any files for tutorials 20-plus. I understand that it must be a ton of work. I do have one suggestion to cut down the work: rather than providing full transcripts with code examples, what if you just provided a code file of the ending state of the code, without any transcript? I think that such code files would be almost as useful as full transcripts, and they would be less work for you to prepare.

Thanks for all you do.

**Comment by elifieldsteel** [comment]
I do, I'm just behind schedule with a bigger-than-usual to-do list.
Providing full transcripts is not actually that much work, because I write
the entire script & code before recording it. The files are just sitting on
my hard drive, I just need to push them to github. Please forgive my
slowness, and I will try to get them up soon. Uploading code-only versions
based on the ending state of the tutorial is a good idea, though that will
take a bit more work (I'd have to re-create those from the videos), but I
will make a note of that and try to add that feature at some point.

Best,
Eli
_______________
Eli Fieldsteel, DMA
Director, University of Illinois Experimental Music Studios
Assistant Professor of Composition-Theory
Office: 217-300-0956
MB 4008, School of Music
1114 W Nevada Street
Urbana, IL 61801

**Comment by bhagerty** [comment]
Thanks for the prompt response! I'll keep my eyes peeled.
